name: flutter_volume_overlay
description: A lightweight Flutter application that displays a system overlay for controlling device volume with auto-fade after 4 seconds.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_overlay_window: ^0.1.0
  perfect_volume_control: ^1.0.6
  permission_handler: ^11.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
